site_name: KK4D
site_url: https://chaimol.com/product/KK4D
nav:
    - Home: index.md
    - 'User Guide': guide.md
    - 'Require software': require.md
    - 'Install': install.md
    - 'Usage': usage.md
    - About: about.md
theme: readthedocs
